image: Visual Studio 2019

init:
    - git config --global core.autocrlf input

shallow_clone: false

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    # - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc16
       
install:
    - git submodule update --init

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="%configuration%" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="D:\FILES\VISUAL STUDIO\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "D:\repos\MxEngine" 2>&1"
1> Working directory: D:\repos\MxEngine\out\build\x64-Debug
    - cmake --build . -j 4
    
