image: Visual Studio 2019

init:
    - git config --global core.autocrlf input

shallow_clone: false

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15
        - TOOLCHAIN: msvc16
       
install:
    - git submodule update --init

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . -j 4 -DCMAKE_BUILD_TYPE="%configuration%" %CMAKE_BUILD_FLAGS%
    
