init:
    - git config --global core.autocrlf input

shallow_clone: false

branches:
  only:
    - master

platform:
    - x64
    
configuration:
    - Debug
    - RelWithDebInfo
    - Release

environment:
    matrix:
      - job_name: Ubuntu 20 and Clang 14
        APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      - job_name: Visual Studio 2022
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      - job_name: Ubuntu 20 and GCC 9
        APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004

matrix:
  exclude:
    - configuration: RelWithDebInfo
      job_name: Ubuntu 20 and GCC 9
    - configuration: RelWithDebInfo
      job_name: Ubuntu 20 and Clang 14

install:
    - git submodule update --init --recursive
      
for:
  - matrix:
      only:
        - job_name: Ubuntu 20 and GCC 
    environment:
      GCC_VERSION: 9
    build_script:
      - gcc --version
      - mkdir build
      - cd build
      - cmake ..
      - cmake --build . -j 4
      
  - matrix:
      only:
        - job_name: Ubuntu 20 and Clang 14
    environment:
      CLANG_VERSION: 14
    build_script:
      - clang --version
      - mkdir build
      - cd build
      - cmake ..
      - cmake --build . -j 4 -DCMAKE_BUILD_TYPE:STRING="%configuration%" -DCMAKE_C_COMPILER="/bin/clang++-14" -D CMAKE_CXX_COMPILER="/bin/clang-14"

  - matrix:
      only:
        - job_name: Visual Studio 2022
    environment:
      VC_VERSION: 17.6
    build_script:
      - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
      - mkdir build
      - cd build
      - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="%configuration%" -DCMAKE_C_COMPILER:FILEPATH="cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="cl.exe"
      - cmake --build . -j 4
