image: Visual Studio 2019

init:
    - git config --global core.autocrlf input

shallow_clone: false

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    # - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc16
       
install:
    - git submodule update --init

build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE:STRING="%configuration%" -G "Ninja"
    - cmake --build . -j 4
    
