language: cpp
dist: bionic
git:
  submodules: false
  
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-bionic-9
        - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-10
        - lldb-10
        - lld-10
        - libstdc++-10-dev
        - xorg-dev
        - libgl1-mesa-dev
        - libxrandr-dev
        - libxinerama-dev
    env:
    - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - LINKER_FLAGS="-std=c++17 -lstdc++fs -stdlib=libstdc++"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - software-properties-common
        - g++-10
        - xorg-dev
        - libgl1-mesa-dev
        - libxrandr-dev
        - libxinerama-dev
    env:
    - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
    - LINKER_FLAGS="-std=c++17 -lstdc++fs -stdlib=libstdc++" 
  - os: windows
    env:
    - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
    install:
    - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
    - choco install dotnetcore-sdk
    - dotnet restore
    
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init
    - eval "${MATRIX_EVAL}"
    
script:
- cmake .
- cmake --build . -j 4
compiler:
- g++
os:
- linux
- windows
