language: cpp
dist: bionic
git:
  submodules: false
  
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-bionic-9
        - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-10
        - lldb-10
        - lld-10
        - libstdc++-8-dev
    env:
    - MATRIX_EVAL="CC=clang-10 && CXX=clang-10"
    - LINKER_FLAGS="-std=c++17 -stdlib=libstdc++"
    
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init
    - eval "${MATRIX_EVAL}"
    
script:
- cmake .
- cmake --build . -j 4
compiler:
- clang
os:
- linux
